In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('..\\data\\segment_4_dataset.csv')
df.head()

,lat,long,age,ihfc_q,ps_q,stein_q,ps_z,stein_z
0,44.6750,-125.285,9.119624,79.0,156.665075,168.881356,3556.955038,3702.253111
1,44.6600,-125.271,9.119624,81.0,156.665075,168.881356,3556.955038,3702.253111
2,44.6600,-125.266,9.119624,93.0,156.665075,168.881356,3556.955038,3702.253111
3,44.6617,-125.260,9.119624,77.0,156.665075,168.881356,3556.955038,3702.253111
4,44.6600,-125.250,9.119624,81.0,156.665075,168.881356,3556.955038,3702.253111

In [29]:
x = df[['long','bathy']]
y = df['lat']

In [30]:
x.head()

      long        bathy
0 -130.392 -2845.584229
1 -130.125 -2697.497559
2 -129.859 -2736.506348
3 -129.592 -2698.546631
4 -129.325 -2554.697510

In [31]:
x.shape

(23, 2)

In [32]:
y.head()

0    47.07474
1    47.07474
2    47.07474
3    47.07474
4    47.07474
Name: lat, dtype: float64

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=3, test_size=0.2)

In [34]:
x_train.shape

(18, 2)

In [35]:
x_test.shape

(5, 2)

In [38]:
x_train.describe().round(3)

          long     bathy
count   18.000    18.000
mean  -127.814 -2244.654
std      1.850   830.498
min   -130.392 -2845.584
25%   -129.258 -2698.284
50%   -128.125 -2649.672
75%   -126.325 -2186.151
max   -124.525   -42.207

In [39]:
x_test.describe().round(3)

          long     bathy
count    5.000     5.000
mean  -126.179 -1887.268
std      0.912  1063.886
min   -127.192 -2602.565
25%   -126.659 -2532.506
50%   -126.392 -2504.866
75%   -125.859 -1692.397
max   -124.792  -104.004